### ISSUE TITLE
Cannot run program "cmd": error=2, No such file or directory

### ISSUE THREAD

**Issue by mavvverick** [woxihuannisja/Bangcle#4]
$ java -jar Bangcle.jar b test.apk
----------Bangcle Automation----------------
/Users/testDesktop/Bangcle/bangcle_tool
apkPath:/Users/testDesktop/Bangcle/bangcle_tool/test.apk decompiledDirName:test
正在反编译/Users/testDesktop/Bangcle/bangcle_tool/test.apk
execute java -jar tools/apktool.jar d /Users/testDesktop/Bangcle/bangcle_tool/test.apk -o /Users/testDesktop/Bangcle/bangcle_tool/output/test -s -f
java.io.IOException: Cannot run program "cmd": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.fengyue.bangcle.SystemCommand.execute(SystemCommand.java:12)
	at com.fengyue.bangcle.Main.main(Main.java:77)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
java.io.FileNotFoundException: /Users/testDesktop/Bangcle/bangcle_tool/output/test/classes.dex (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.fengyue.bangcle.FileUtil.getFileByte(FileUtil.java:96)
	at com.fengyue.bangcle.Main.main(Main.java:102)
java.lang.IllegalArgumentException: Null input buffer
	at javax.crypto.Cipher.doFinal(Cipher.java:2160)
	at com.fengyue.bangcle.AESUtil.encrypt(AESUtil.java:49)
	at com.fengyue.bangcle.Main.main(Main.java:103)
AES encrypt classes.dex finished
java.lang.NullPointerException
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at com.fengyue.bangcle.FileUtil.byteToFile(FileUtil.java:151)
	at com.fengyue.bangcle.Main.main(Main.java:105)
copy jiami.dat to assets dir finished
反编译失败

**Comment by WolfHami** [comment]
Same problem me 😭😭 did u get any solution

**Comment by er28-0652** [comment]
I had same issue. Upon checking following, it seems that this script is supposed to be executed in Windows.

https://github.com/woxihuannisja/Bangcle/blob/master/bangcle_tool/src/com/fengyue/bangcle/SystemCommand.java#L12 

I tried to run in Windows, it worked.
